#ifndef __OPTIONS_H
#define __OPTIONS_H

#define LOGICAL_WIDTH_PX 400
#define LOGICAL_HEIGHT_PX 300

#define ASTEROID_RADIUS 0.032f
#define ASTEROID_ROT_SPEED_MIN -0.5f
#define ASTEROID_ROT_SPEED_MAX 0.5f

#define FONT_WIDTH 0.04f
#define FONT_SPACE 0.0025f

#define SCORE_DIGITS 7
#define SCORE_BUFFER_SIZE (SCORE_DIGITS + 1)

#define MAX_SCORES 10
#define MAX_SPEED 0.75f

#define NUM_SOUNDS 5
#define SOUND_BEAT1 0
#define SOUND_BEAT2 1
#define SOUND_EXPLOSION 2
#define SOUND_PHASER 3
#define SOUND_THRUSTER 4

#define POINTS_PER_HIT 20
#define NO_ASTEROID_RADIUS_RESPAWN 0.12f
#define TITLE_ASTEROIDS 5
#define START_LEVEL_DELAY_MS 2000.0f
#define NEXT_WAVE_DELAY 3.0f

#define GAMEOVER_COUNTDOWN 1.0f
#define GAMEOVER_DELAY 3.0f

#define HIGHSCORES_FILE "highscores.csv"

#endif
